language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-rw https://${GITHUB_TOKEN}@github.com/bluzelle/bluzelle-py.git
- bumpversion --verbose minor
- git push --set-upstream origin-rw HEAD:devel
script:
- python3 -c "print('future integration test here')"
deploy:
  provider: pypi
  user: "${PYPI_USER}"
  server: https://test.pypi.org/legacy/
  password:
    secure: jv+K38tR8JnXMeEqs+7g7YDOTLvtqDfVwGn1piFoqq1dt/PEZBLW1JhTgDQA2M2diAOa8KnXLRnlqhyCcZaJaP4HB96WykojLIfIJJF+B5ypWs1ZKA3JUEfruOwfXBUf08E+Uc9yob9T8bDBnA6deNkEULqAkF9ZiceJnTSRzOxr4Gc9U6T0gBeRRHYg4gs5MBVaXKXtZh+Fzdk8y/aDJRTT06tPG1q2h9qJRyfW1XDKKme7x4nmG5al+aWKMayIKlzlv5DiWnQL8mX60bIk1/mA1WK3N6mo2tmISOAgdRh1XsG+1vCMsCCk2mZXES7gfDe9TS/YeuNYL/00ULXkO1609ARFfo0SDtydS9jijAjicOiwdWkfTRTp5kq0ikrgp7AsdS168rK9hlBdUmutUiDKV65Vv37fJ79cBqf/bmFrpUTkxlBYCg5fj3n8CaJ/G09HjZD90acz+bpIYwkz0/wpKueBYp0ilbF2E9hIvAZjqK9xWlL63wafbmO/uzkM6Qsx/S5XOBt5pj5IDlb7T2X7ukxMIPTcXURcUbrHvDI0VBg0D+kmiPcExVuB8vdf8Cusf6GCeWPxjBkwYdwg+PAJRgvh+LnPFxex0UjFJnGJHq1SEQGBTPc8H9faUOUuBSNFRszy7rfmZc09mYgx59z+2FNOys3v9ztLeAxZq98=
  on:
    branch: devel
