language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-rw https://${GITHUB_TOKEN}@github.com/bluzelle/bluzelle-py.git
- bumpversion --verbose minor
- git push --set-upstream origin-rw HEAD:devel
script:
- python3 -c "print('future integration test here')"
deploy:
  provider: pypi
  user: "${PYPI_USER}"
  server: https://test.pypi.org/legacy/
  password:
    secure: LdMl0vpj0fZRjDJRwJatYuox66kmmgQBNiAuqpsFjLOwR1gtrD7b6dOypQ/rexpF6az7brMcKvFfp3So/s6YpowmajLmv5M/yKEoi+oCJXriMZdry+qX2qWTa3C4llpIRmQlt33vemoBsi0e45HrT4A78GIemeZgxXzRSmBh6c9z34UFR1jKU3LOMvBrWb37RuW2a49/zvo9wWdMcgqgmI1q9hbJMGUhe80bYt7TMZTU/dAAWgoCYWpMswFEOTRUchU9TxHuIYN3lT+y4s7v6yXxXs0C9QZ+PdIQVjkPdsph0DDYjGggYAjNHSeoUh5Lv8IJin+u+qY9DfmdaiWwxuYzcSib0olp41c22QrPOOI/7VDJ4f0Iqro0JbBaJIWhAipVSxw0A7sEbPPPtkAznV+yQqMIF9am2SDShM6mxWmVNQY+3s93MnNDcbO8JCZ8TzDPbt1tgdlUfqE3PVJx+D0/RPGkb2DaXtwHYtiPjjKxlxKt+0UtxVDs8XlFID1o6W/AadQkh1WcLnWD3L8zQ+T94NYdBfebWnr7btGs1/PX6zzEMDgsKDgSkSIQ0+H7Go8JFAAXRHerUkhdG8zXp9iHbsorTkLoiQbkac7gId4P8s8hHsjAWkH5fH2wqaee6cRMC7IuVlX+3TL1ECCymojXIlBHe1cFnO1mDBWIH+k=
  on:
    branch: devel
