language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_script:
- find . -type f -name '*.tar.gz' -delete
- git config --global lfs.fetchexclude "*"
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-rw https://${GITHUB_TOKEN}@github.com/bluzelle/bluzelle-py.git
- bumpversion --verbose minor --allow-dirty
- git push --set-upstream origin-rw HEAD:devel
script:
- python3 -c "print('future integration test here')"
deploy:
  provider: pypi
  user: "${PYPI_USER}"
  server: https://test.pypi.org/legacy/
  password:
    secure: ajVBpH4cXyF6n+8/l0eqXn9jJaxs2e2gq9RvHVbrVQ3DitdlvODihUcT9KZMOCZt6mdsm+/hlopximpdFTXbXQhEoU1NIwHhH1UmfIvhboB2NO4EVlG9oxzY/l1u02s2Qi83mqMws1gZFOKJwiwRK3g3SKhi4s0XB0E6yrfkEZlOOzI861mIiE8c48aAy1B1hkdsgUykYf811FW2dbLGO2RgNggcl2mhkIIhR4m3l9j0dx4LNcKdB4T0Vun+/fl4TmfA/m8TvgK2b+ReYh3RgbDrPvQukh5fBy0qpNDfSdR4GwLkT6Mac1upDMtEbdBDJy9avQTvtgFznsBP3xjfrvzuJ39NaCtct9qus40064Zj2ELmNuuoy1rGR8SBgmVSeF5Lb3IRahZxCMthn0fltvQ9mS5AbGGJV7/j7LuBSsDvK0nC49fFHRy9zgUKchDl32Nrwusfu7ay4XoTRBsfxdxiYPH15gXBVeX02kwKtS2Kk/ZGWWVRWuv07yQielM2tqowP8MnNkiS8fU0DUHWV1vjw8lNKfBoPn7fJFTbvGpl/S0f6fYsp8iC6dpPYbHxk7dY6W4jPva3Y4q48XX7o5a2v4vBCWeMOSjfbkfVbYsvLSz+fwkE9MKOS0ajcyAZy0yjmoVqkOQ5soJkOrS6/uayOuXLM466UXjRK8fOSgQ=
  on:
    branch: devel
