language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-rw https://${GITHUB_TOKEN}@github.com/bluzelle/bluzelle-py.git
- bumpversion --verbose minor
- git push --set-upstream origin-rw HEAD:devel
script:
- python3 -c "print('future integration test here')"
deploy:
  provider: pypi
  user: "${PYPI_USER}"
  server: https://test.pypi.org/legacy/
  password:
    secure: SowYqQy3B+MwXBNBilRsM7cro5zh6fYhj1uFU0MCl2lgYSd3BOzreljvuCg3NgzI+jes47D6GuUlJl/E2fwTOBAzP24jAnGWzGPvKD4k3PJ559+rpOPQ63/mI8T/V4ns4B9dtl4ft0elga8MwgAZM8KXyJufpur8VEXfGWz/52WxaUNYy7J/4ydYuQdNnvv6l2+RFcNAT0YTvT/M59zl4mWa3/aSUENaC8U0HpOmlYHnsBW/ewyN/GE596NWjZ4BbKR1hwtYUa7tfGtDPFRMAW7E5zr4DaFqzs1W3I9Q/WSkkPbeVAikUzKJCZpnsxBlanmeFL6sbnng6285DREKtgWrufrncqmzSFuG+00OcPkj1KXPzZPiJa/cu+lyQL1wdfwAx5KWFJPvCD/wjnlB6L8ht/9p5lZufmSeTDe+p4V0cCUVJ/hzOFINGHFZ6rHI7RgC5opurSUqZGwktGoUsEW+4Mp2XFnDRt3Hpk/oks/GsS0ftMNEijvYCUR/mQEwIXQl7wQAI8yVHu59/+VfODmbikJTb0VvN5r8WRBYwccllPcF9/67MAJC6p+Rz/6b4C4+bN7IB4GUXfqAyKnvbHjK2fez69y2Pnjuqy4wdc6KQM23rJJ5TrUw8KpBf7Gy3VhD+k4VqWP0aY8Sdvi/Ju+C4TQ0ZAr5SaP1yhVVcMc=
  on:
    branch: devel
