# some parts taken from https://gist.github.com/willprice/e07efd73fb7f13f917ea
language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-rw https://${GITHUB_TOKEN}@github.com/bluzelle/bluzelle-py.git
- bumpversion --verbose minor
- git push --set-upstream origin-rw HEAD:devel
script:
- python3 -c "print('future integration test here')"
deploy:
  provider: pypi
  user: "${PYPI_USER}"
  server: https://test.pypi.org/legacy/
  password:
    secure: Hjch9zed9xdWxQIaBZ9Q8pROcKp0RROyMB5Gv9Tz7vJb93og0RZHIFPuwy5VFlwE9fSklkPR8j4eo92kUfLC4R6DZ6qdFs/iZVd2hWZu0kK7kM9vIAHg309En9+Y80cuUbvO/+gNEe/84M3ioc2YiuuQpcahEQmhLb+ups9mPxluoBQxXzh3+av16/RCy7o6JwihDRByRns98Pnm778YIQEP2UMM4N6CfkHHXGIW9nkmp9tMFuE6rSluLlhcfHoTV7Tue8S9J1OFox/q+Ij+zx717PHOQ1RMERyUHcBKoDg9s1FuKqY2BZvnqXrffIcnj+w+jHBrBXFSbYt90me4ZU4+7NmOMo3sDHnQWmj1bBSVBMWZDxyKhwu7Ho4wxbAJsotCUvsTvrSAm8d/1eIprbhOYgZ+ecM0y1NApVCRJWQjdQlIO5BlfD0nig7SsblLbA6DHmCqKa2KuW2Dim0svNJbd8DEhdQjb6LTdUo3TS76vkiz9yWfeqZBbGSofJYSot7/2Zxko+0mJYTXcy3UxU2R+XYQ2fPUnAIX8++WKB9Ggp60AZibLyn5/8cAKIJeOcxjj9LzCcUv+iPnO55VTowfEFtzozwwOpMqpk+xjl7c3HjIis2SRkIP4I6AYe0TrwMeLGGsH/S8r99T6BjYS9p6H2BzwuV5QTPgxUK6S+w=
  on:
    branch: devel
