language: python
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
before_script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git remote add origin-rw https://${GITHUB_TOKEN}@github.com/bluzelle/bluzelle-py.git
- bumpversion --verbose minor
- git push --set-upstream origin-rw HEAD:devel
script:
- python3 -c "print('future integration test here')"
deploy:
  provider: pypi
  user: "${PYPI_USER}"
  server: https://test.pypi.org/legacy/
  password:
    secure: iV75SzDiUGi3u5OmQH3+gcDjDiEyao76V/D7hjAhxBrPMmOVFHb3eSavDAfNUTilA9o/0wYUt9lnd7EG2JeNE4DrIQJB+MDdKJ4iC3IZkuw//hcVjp82D3vVwtcgllHpen1JvblHntDpKCbG2i/DK6cYKWTSRSceCQOzWLdZkaPlbEG1H0pNXWkWekSKJG4CwszUaLujBanZgWBYCFC8Y99SVfJOS2Yne6NHwnze6Wzm8UCdRVZZem4XJPoD0lkL3PFur4CXJiOPoO+wHRSVqtFbya4rg/dSNIjd6y9svlfyvTtm4+aIHD1vJsG2azwIEzn1GVu0xWSfWcyrlcy6wDPH/W+5zYppW6uBNNXjRHPuDFKxIo7LXoFGQJfTxWg+KIwJ72coJRrwByFrSUyC1r4CXqZRIp5LTw4iDM5Vy6PN5r+MVAmQwNwUuJ65n6vmf7pnumyF5LuRJf/zeN0ONLqdKrmek2pT1DtMuxjRQFxVno8AHvI3c7B9ukcHycHbd1xkUMHvVKcG4VHsuJFIoDnVBHwJMbLtzBKQ/oaTkBYh7EXmaDJAq44HF/d8moD4buFXx/5BJPVg7DTC6jyYZfWCjpzAvEXSTGcL3gQj9CWGqCqxyMD2R2PR0FzkIug7HP/7+w1I5oe9iGSy32JWKAkLICrxoI/U4nO04QOMD5M=
  on:
    branch: devel
